[project]

site_name = "Linkual Log"
site_description = "Official implementation of linkual log"
site_author = "Sergio Gao"
site_url = "https://eng.shujie.com/"
copyright = "Copyright &copy; 2026 Sergio Gao"
repo_url = "https://github.com/gsjz/linkualog"
repo_name = "gsjz/linkualog"

nav = [
    { "获得开始" = "index.md" },
    { "每日词汇" = "dictionary/daily/index.md" },
    { "CET" = "dictionary/cet/index.md" },
    { "IELTS" = "dictionary/ielts/index.md" }
]

#extra_css = ["stylesheets/extra.css"]
extra_javascript = ["extra/extra.js"]

[project.theme]

#custom_dir = "overrides"
#favicon = "images/favicon.png"
language = "zh"

features = [
    "announce.dismiss",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.path",
    "navigation.sections",
    "navigation.top",
    "navigation.tracking",
]


[project.theme.icon]
logo = "lucide/book-marked"

[project.theme.font]
text = "Inter"
code = "Jetbrains Mono"

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/gsjz"
